# Generated by Django 2.0.4 on 2018-05-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('label', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
